apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
    tier: backend
spec:
  selector:
    matchLabels:
      app: notification
      tier: backend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notification
        tier: backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      initContainers:
        - name: notification-run-migration
          image: felixle236/k8s-micro-notification-service
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', './node_modules/typeorm/cli.js -f dist/configs/DbConfig migration:run']
          volumeMounts:
            - mountPath: /usr/app/.env
              subPath: .env
              name: notification-volume
              readOnly: true
      containers:
        - name: notification-container
          image: felixle236/k8s-micro-notification-service
          imagePullPolicy: IfNotPresent
          resources:
            limits: {}
              # cpu: 400m
              # memory: 600Mi
            requests: {}
              # cpu: 300m
              # memory: 400Mi
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 3001
              protocol: TCP
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/app/.env
              subPath: .env
              name: notification-volume
              readOnly: true
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: notification-volume
          secret:
            secretName: notification-secret
            items:
              - key: .env
                path: .env
