apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
    tier: backend
spec:
  selector:
    app: notification
    tier: backend
  ports:
    - name: notification-port
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: notification-internal-port
      port: 3001
      targetPort: 3001
      protocol: TCP
    - name: notification-apidoc-port
      port: 4000
      targetPort: 4000
      protocol: TCP
