apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pgadmin-secret
  namespace: prod
  labels:
    app: pgadmin
    tier: database
data:
  pgadmin_email: YWRtaW5AZG9tYWluLmNvbQ==
  pgadmin_password: RGVtb0AxMjM=
