apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJuYW10ZWNodGVhbSIsInBhc3N3b3JkIjoiTmFtdGVjaDg4IiwiZW1haWwiOiJqb2huQG5hbXRlY2guY29tLmF1IiwiYXV0aCI6ImJtRnRkR1ZqYUhSbFlXMDZUbUZ0ZEdWamFEZzQifX19
