apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication
    tier: backend
spec:
  selector:
    app: authentication
    tier: backend
  ports:
    - name: authentication-port
      port: 80
      targetPort: 3000
      protocol: TCP
